version: '3.8'
services:
  clientes-api:
    build: ./ClientesService
    ports:
      - "5001:8080"
    depends_on:
      - clientes-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  clientes-db:
    image: postgres
    container_name: clientes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Univalle12
      POSTGRES_DB: clientesdb
    ports:
      - "5433:5432"

  productos-api:
    build: ./ProductosService
    ports:
      - "5002:8080"
    depends_on:
      - productos-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  productos-db:
    image: postgres
    container_name: productos-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Univalle12
      POSTGRES_DB: productosdb
    ports:
      - "5434:5432"

  ventas-api:
    build: ./VentasService
    ports:
      - "5003:8080"
    depends_on:
      - ventas-db
      - clientes-api
      - productos-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ventas-db:
    image: postgres
    container_name: ventas-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Univalle12
      POSTGRES_DB: ventasdb
    ports:
      - "5435:5432"
